blank_issues_enabled: false
contact_links:
  - name: ðŸ’¡ Feature Request
    url: https://github.com/remix-run/react-router/discussions/new?category=proposals
    about: If you've got an idea for a new feature in React Router, please open a new Discussion with the `Proposals` label
  - name: ðŸ¤” Usage Question (Github Discussions)
    url: https://github.com/remix-run/remix/discussions/new?category=q-a
    about: Open a Discussion in GitHub wih the `Q&A` label
  - name: ðŸ’¬ Remix Discord Channel
    url: https://rmx.as/discord
    about: Interact with other people using React Router and Remix ðŸ“€
