name: ğŸšª Close issues without a reproduction

on:
  workflow_dispatch:
    inputs:
      dryRun:
        type: boolean
        description: "Dry Run? (no issues will be closed)"
        default: "false"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  close-no-repro-issues:
    name: ğŸšª Close issues without a reproduction
    if: github.repository == 'remix-run/react-router'
    runs-on: ubuntu-latest
    env:
      CI: "true"
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4

      - name: ğŸ“¦ Setup pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: â” Setup node
        uses: actions/setup-node@v4
        with:
          # required for --experimental-strip-types
          node-version: 22
          cache: "pnpm"

      - name: ğŸ“¥ Install deps
        run: pnpm install --frozen-lockfile

      - name: ğŸšª Close Issues (Dry Run)
        if: github.event.inputs.dryRun == "true"
        run: node --experimental-strip-types ./scripts/close-no-repro-issues.ts --dryRun

      - name: ğŸšª Close Issues
        if: github.event.inputs.dryRun != "true"
        run: echo "Running script for real" # node --experimental-strip-types ./scripts/close-no-repro-issues.ts
