# This is a bulk-close script that was used initially to find and close issues
# without a repro, but moving forward we'll likely use the singular version
# (close-no-repro-issue.yml) on new issues which is driven by a label added to
# the issue

name: ğŸšª Close issues without a reproduction

on:
  workflow_dispatch:
    inputs:
      dryRun:
        type: boolean
        description: "Dry Run? (no issues will be closed)"
        default: false

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  close-no-repro-issues:
    name: ğŸšª Close issues
    if: github.repository == 'remix-run/react-router'
    runs-on: ubuntu-latest
    env:
      CI: "true"
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v5

      - name: ğŸ“¦ Setup pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: â” Setup node
        uses: actions/setup-node@v5
        with:
          # required for --experimental-strip-types
          node-version: 22
          cache: "pnpm"

      - name: ğŸ“¥ Install deps
        run: pnpm install --frozen-lockfile

      - name: ğŸšª Close Issues (Dry Run)
        if: ${{ inputs.dryRun }}
        run: node --experimental-strip-types ./scripts/close-no-repro-issues.ts --dryRun

      - name: ğŸšª Close Issues
        if: ${{ ! inputs.dryRun }}
        run: node --experimental-strip-types ./scripts/close-no-repro-issues.ts
