# Close a singular pull request that implements a feature that has not
# gone through the Proposal process
# Triggered by adding the `feature-request` label to an issue

name: ğŸšª Close Feature Pull Request

on:
  pull_request:
    types: [labeled]

jobs:
  close-feature-pr:
    name: ğŸšª Close Feature Pull Request
    if: github.repository == 'remix-run/react-router' && github.event.label.name == 'feature-request'
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4

      - name: ğŸšª Close PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} -F ./scripts/close-feature-pr.md
          gh pr edit ${{ github.event.pull_request.number }} --remove-label ${{ github.event.label.name }}
          gh pr close ${{ github.event.pull_request.number }}
