name: ğŸ“š Docs

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to generate docs for"
        required: true
      api:
        description: "API Names to generate docs for"
        required: false
        default: ""

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    if: github.repository == 'remix-run/react-router'
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.FORMAT_PAT }}
          ref: ${{ github.event.inputs.branch }}

      - name: ğŸ“¦ Setup pnpm
        uses: pnpm/action-setup@v4

      - name: â” Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - name: ğŸ“¥ Install deps
        run: pnpm install --frozen-lockfile

      - name: ğŸ— Build
        run: pnpm build

      - name: ğŸ“š Generate Typedoc Docs
        run: pnpm run docs

      - name: ğŸ“š Generate Markdown Docs (for all APIs)
        if: github.event.inputs.api == ''
        run: node --experimental-strip-types scripts/docs.ts --path packages/react-router/lib/hooks.tsx --write

      - name: ğŸ“š Generate Markdown Docs (for specific APIs)
        if: github.event.inputs.api != ''
        run: node --experimental-strip-types scripts/docs.ts --path packages/react-router/lib/hooks.tsx --write --api ${{ github.event.inputs.api }}

      - name: ğŸ’ª Commit
        run: |
          git config --local user.email "hello@remix.run"
          git config --local user.name "Remix Run Bot"

          git add .
          if [ -z "$(git status --porcelain)" ]; then
            echo "ğŸ’¿ no docs changed"
            exit 0
          fi
          git commit -m "chore: generate markdown docs from jsdocs"
          git push
          echo "ğŸ’¿ pushed docs changes https://github.com/$GITHUB_REPOSITORY/commit/$(git rev-parse HEAD)"
