name: PR (Full)

# PRs touching react-router-dev will also run on Windows and OSX

on:
  pull_request:
    paths:
      - "package.json"
      - "pnpm-lock.yaml"
      - "packages/react-router-dev/**"
      - "!**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-firefox:
    name: "ðŸ‘€ Integration Test"
    if: github.repository == 'remix-run/react-router'
    uses: ./.github/workflows/shared-integration.yml
    with:
      os: "ubuntu-latest"
      node_version: "[20]"
      browser: '["firefox"]'

  integration-msedge:
    name: "ðŸ‘€ Integration Test"
    if: github.repository == 'remix-run/react-router'
    uses: ./.github/workflows/shared-integration.yml
    with:
      os: "windows-latest"
      node_version: "[20]"
      browser: '["msedge"]'

  integration-webkit:
    name: "ðŸ‘€ Integration Test"
    if: github.repository == 'remix-run/react-router'
    uses: ./.github/workflows/shared-integration.yml
    with:
      os: "macos-latest"
      node_version: "[20]"
      browser: '["webkit"]'
