name: Branch

# main/dev/release-* branches will get the full run across
# all OS/browsers for multiple node versions

on:
  push:
    branches:
      - main
      - dev
      - release-*
    tags:
      - "v0.0.0-nightly-*"
    paths-ignore:
      - ".changeset/**"
      - "decisions/**"
      - "docs/**"
      - "examples/**"
      - "jest/**"
      - "scripts/**"
      - "tutorial/**"
      - "contributors.yml"
      - "**/*.md"

jobs:
  build:
    name: "âš™ï¸ Build"
    if: github.repository == 'remix-run/react-router'
    uses: ./.github/workflows/shared-build.yml

  integration-ubuntu:
    name: "ğŸ‘€ Integration Test"
    if: github.repository == 'remix-run/react-router'
    uses: ./.github/workflows/shared-integration.yml
    with:
      os: "ubuntu-latest"
      node_version: "[20, 22]"
      browser: '["chromium", "firefox"]'

  integration-windows:
    name: "ğŸ‘€ Integration Test"
    if: github.repository == 'remix-run/react-router'
    uses: ./.github/workflows/shared-integration.yml
    with:
      os: "windows-latest"
      node_version: "[20, 22]"
      browser: '["msedge"]'

  integration-macos:
    name: "ğŸ‘€ Integration Test"
    if: github.repository == 'remix-run/react-router'
    uses: ./.github/workflows/shared-integration.yml
    with:
      os: "macos-latest"
      node_version: "[20, 22]"
      browser: '["webkit"]'
