name: PR (Full)

# PRs touching @react-router/dev will also run on Ubuntu/Firefox, Windows/Edge and
# OSX/WebKit as well as an Ubuntu/Chromium run on  Node 20.18.

on:
  pull_request:
    paths:
      - "pnpm-lock.yaml"
      - "integration/**"
      - "packages/react-router-dev/**"
      - "!**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-chromium:
    name: "ðŸ‘€ Integration Test"
    if: github.repository == 'remix-run/react-router'
    uses: ./.github/workflows/shared-integration.yml
    with:
      os: "ubuntu-latest"
      node_version: "[20.18]"
      browser: '["chromium"]'

  integration-firefox:
    name: "ðŸ‘€ Integration Test"
    if: github.repository == 'remix-run/react-router'
    uses: ./.github/workflows/shared-integration.yml
    with:
      os: "ubuntu-latest"
      node_version: "[22]"
      browser: '["firefox"]'

  integration-msedge:
    name: "ðŸ‘€ Integration Test"
    if: github.repository == 'remix-run/react-router'
    uses: ./.github/workflows/shared-integration.yml
    with:
      os: "windows-latest"
      node_version: "[22]"
      browser: '["msedge"]'
      timeout: 90

  integration-webkit:
    name: "ðŸ‘€ Integration Test"
    if: github.repository == 'remix-run/react-router'
    uses: ./.github/workflows/shared-integration.yml
    with:
      os: "macos-latest"
      node_version: "[22]"
      browser: '["webkit"]'
