name: ðŸ¥º No Response

on:
  schedule:
    # Schedule for five minutes after the hour, every hour
    - cron: "5 * * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    if: github.repository == 'remix-run/react-router'
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ¥º Handle Ghosting
        uses: actions/stale@v8
        with:
          close-issue-message: >
            This issue has been automatically closed because we didn't hear
            anything from the original author after the previous notice.
          close-pr-message: >
            This PR has been automatically closed because we didn't hear
            anything from the original author after the previous notice.
          stale-issue-label: needs-response
          stale-issue-message: >
            This issue has been automatically marked stale because we haven't
            received a response from the original author in a while ðŸ™ˆ. This
            automation helps keep the issue tracker clean from issues that are
            not actionable. Please reach out if you have more information for us
            or you think this issue shouldn't be closed! ðŸ™‚ If you don't do so
            within 7 days, this issue will be automatically closed.
          stale-pr-label: needs-response
          stale-pr-message: >
            This PR has been automatically marked stale because we haven't
            received a response from the original author in a while ðŸ™ˆ. This
            automation helps keep the issue tracker clean from issues that are
            not actionable. Please reach out if you have more information for us
            or you think this issue shouldn't be closed! ðŸ™‚ If you don't do so
            within 7 days, this PR will be automatically closed.
