name: ğŸ§ª Stage 2 (Alpha) Release

on:
  pull_request:
    types: [labeled]

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  CI: true

jobs:
  alpha:
    name: ğŸ§ª Alpha Release
    if: github.repository == 'remix-run/react-router' && github.event.label.name == 'alpha-release'
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: ğŸ“¦ Setup pnpm
        uses: pnpm/action-setup@v4

      - name: â” Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: ğŸ“¥ Install deps
        run: pnpm install --frozen-lockfile

      - name: Test
        run: git log -n 1

      - name: â¤´ï¸ Update version
        id: version
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          NEXT_VERSION=0.0.0-alpha-${SHORT_SHA}
          git checkout -b alpha/${NEXT_VERSION}
          pnpm run version ${NEXT_VERSION}
          echo "version=${NEXT_VERSION}" >> "$GITHUB_OUTPUT"

      - name: ğŸ— Build
        run: pnpm build

      - name: Check
        run: |
          echo "Version: ${{ steps.version.outputs.version }}"
          git status
          cat packages/react-router/package.json
          cat packages/react-router-dev/package.json
          ls packages/react-router/dist
          ls packages/react-router-dev/dist

      # - name: ğŸ” Setup npm auth
      #   run: |
      #     echo "registry=https://registry.npmjs.org" >> ~/.npmrc
      #     echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      # - name: ğŸš€ Publish
      #   run: pnpm run publish
