name: üß™ Stage 2 (Alpha) Release

on:
  pull_request:
    types: [labeled]

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  CI: true

jobs:
  alpha-release:
    name: üß™ Alpha Release
    if: github.repository == 'remix-run/react-router' && github.event.label.name == 'alpha-release'
    runs-on: ubuntu-latest
    steps:
      - name: üìÑ Log Info
        run: |
          echo "Label: ${{ github.event.label.name }}"
          echo "Branch: ${{ github.event.pull_request.head.ref }}"
          echo "SHA: ${{ github.event.pull_request.head.sha }}"

      - name: ‚¨áÔ∏è Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Log Git Info
        run: |
          git log -n 1
          git status

      - name: üì¶ Setup pnpm
        uses: pnpm/action-setup@v4

      - name: ‚éî Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: üì• Install deps
        run: pnpm install --frozen-lockfile

      - name: ‚§¥Ô∏è Update version
        id: version
        run: |
          git config --local user.email "hello@remix.run"
          git config --local user.name "Remix Run Bot"
          SHORT_SHA=$(git rev-parse --short HEAD)
          NEXT_VERSION=0.0.0-experimental-${SHORT_SHA}
          git checkout -b experimental/${NEXT_VERSION}
          pnpm run version ${NEXT_VERSION}
          echo "version=${NEXT_VERSION}" >> "$GITHUB_OUTPUT"

      - name: üèó Build
        run: pnpm build

      - name: üîê Setup npm auth
        run: |
          echo "registry=https://registry.npmjs.org" >> ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - name: üöÄ Publish
        run: pnpm run publish

      - name: üí¨ Comment
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          LATEST=$(gh release list --limit 1 --json tagName --jq ".[0].tagName")
          echo "Latest release: ${LATEST}"
          echo "Base: ${{ github.event.pull_request.base.sha }}"
          COMMAND="git log --pretty=oneline ${LATEST}..${{ github.event.pull_request.base.sha }}"
          echo -e \
            "Alpha release created: \`${{ steps.version.outputs.version }}\`\n\n\
            ‚ö†Ô∏è **Note:** This release was created from the \`HEAD\` of this branch so it \
            may contain commits that have landed in \`dev\` but have not been released yet \
            depending on when this branch was created. You can run the following command \
            to see the commits that may not have been released yet:\n\n\
            \`\`\`bash\n\
            ${COMMAND}\n\
            \`\`\`" \
            | gh pr comment ${{ github.event.pull_request.number }} --body-file -
          gh pr edit ${{ github.event.pull_request.number }} --remove-label ${{ github.event.label.name }}
